name: Build blueberry-k3s image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: blueberry-k3s
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-k3s:
    runs-on: ubuntu-24.04-arm
    if: |
      github.event_name != 'push' ||
      (
        startsWith(github.event.head_commit.message, 'feat:') ||
        startsWith(github.event.head_commit.message, 'fix:') ||
        startsWith(github.event.head_commit.message, 'perf:') ||
        startsWith(github.event.head_commit.message, 'revert:')
      )

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile.k3s
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          oci: false

      - uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: latest

